// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK1D_WfKCRBZpQA0Je1BdFzqx_GxxyGrs',
    appId: '1:391697565948:android:899a2a132d9631abe82f79',
    messagingSenderId: '391697565948',
    projectId: 'fir-7154f',
    databaseURL: 'https://fir-7154f.firebaseio.com',
    storageBucket: 'fir-7154f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc6j9DOSCqd94UGt65ng0LL0Ss54lUhHU',
    appId: '1:391697565948:ios:1dc82cb40dc23ce2e82f79',
    messagingSenderId: '391697565948',
    projectId: 'fir-7154f',
    databaseURL: 'https://fir-7154f.firebaseio.com',
    storageBucket: 'fir-7154f.appspot.com',
    androidClientId: '391697565948-6ps0vn6qr6nugkepo6nhigmtu25o7i8d.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAdv3',
  );
}
